[project]
name = "cognitive-design-framework"
version = "0.1.0"
description = "Meta-Optimized Hybrid Reasoning Framework"
authors = ["Ryan Oates <ryan_oates@my.cuesta.edu>"]
channels = ["conda-forge", "modular"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = ">=3.8"
mojo = "*"

[tasks]
test = "python -m pytest tests/"
test-unit = "python -m pytest tests/unit/"
test-integration = "python -m pytest tests/integration/"
test-performance = "python -m pytest tests/performance/"
analyze = "python tools/analysis/complexity_analysis.py"
benchmark = "python tools/analysis/performance_benchmark.py"
format = "mojo format ."
lint = "mojo check ."

[feature.dev.dependencies]
pytest = "*"
black = "*"
mypy = "*"

[environments]
default = ["dev"]
