#!/usr/bin/env python3
"""
bootstrap.py
Heals all .mojo stubs so `pixi run format` succeeds.
Run once:  pixi run bootstrap
"""
import os, pathlib, textwrap

STUB_TEMPLATE = textwrap.dedent('''
    # Place-holder module generated by bootstrap.py
    fn main() -> None:
        print("Hello from cognitive-design-framework")
''').lstrip()

for path in pathlib.Path('.').rglob('*.mojo'):
    try:
        content = path.read_text(encoding='utf-8')
    except Exception:
        continue
    # Only patch obvious stubs (empty, pass-only, or un-parseable)
    stripped = content.strip()
    if not stripped or stripped in {'pass', '"""', 'fn main() -> None:\n    pass'}:
        path.write_text(STUB_TEMPLATE)
        print(f"✅ Healed {path}")